version: '3.5'

services:
  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
    - 2181:2181
    networks:
    - datalabframework

  kafka:
    image: bitnami/kafka:2
    environment:
      KAFKA_ZOOKEEPER_CONNECT:  "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    networks:
    - datalabframework
    volumes:
    - data:/bitnami/kafka

networks:
  datalabframework:
    external: true

volumes:
  data:
