version: "3"

services: 
  prometheus: 
    image: prom/prometheus
    container_name: prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks: 
      - python_logging

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: 
      - "3000:3000"
    links: 
      - prometheus
    networks: 
      - python_logging
    
networks: 
  python_logging:
  